version: '3.8'

services:
  users-db:
    image: postgres:15
    container_name: users-db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data
    networks:
      - users-network

  users-service:
    build: .
    container_name: users-service
    environment:
      - PORT=3000
      - DB_HOST=users-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=users_db
      - JWT_SECRET=your-secret-key
      - MESSAGING_SERVICE_URL=http://messaging-service:3005
    ports:
      - "3000:3000"
    depends_on:
      - users-db
    networks:
      - users-network

volumes:
  users_db_data:

networks:
  users-network:
    driver: bridge